### ISSUE TITLE
Switch to headers.get()

### ISSUE THREAD

**Issue by jeffposnick** [deanhume/Service-Workers-WebP#1]
Wonderful project, and it's great to see service workers being put to creative use!

Quick suggestion for you—instead of filtering through all the headers one by one via `var acceptHeader = headers.find(item => item[0] == 'accept');`, you can use `event.request.headers.get('accept')` to get it directly (and if you're concerned that it may not be present, checking first via `event.request.headers.has('accept')`.

There's an example of that in action at https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/custom-offline-page/service-worker.js#L33 and the docs covering what the `Headers` object supports are at https://fetch.spec.whatwg.org/#headers

**Comment by deanhume** [comment]
Hey Jeffrey

Thanks for reaching out. Great spot and thanks for the advice - that is
much easier, Ill get that updated!

Thanks for your help!
Dean

**Comment by deanhume** [comment]
I've updated the code with your suggestion - thanks for the help!

**Comment by jeffposnick** [comment]
:fireworks:
